configuration:
  swagger:
    app: 'CineBH API'
    description: 'CinemaApp is a web-based ticketing application that allows online movie ticket purchases for a specific movie company with multiple subsidiaries across the country/world.'
    developer: 'Edin Bajrić'
    email: 'edin.bajric@stu.ibu.edu.ba'
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddlAuto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
security:
  jwt:
    secret: ${JWT_SECRET}
email:
  mailgun:
    domain: ${MG_DOMAIN}
    from-email: ${MG_FROM_EMAIL}
    username: api
    password: ${MG_PASSWORD}
